package dbcodegen

case class DataColumn(
  name: String,
  scalaType: String,
  isAutoGenerated: Boolean,
  isPartOfPrimaryKey: Boolean,
) {
  def scalaName = NameFormat.sanitizeScalaName(NameFormat.toCamelCase(name))
}

case class DataTable(
  name: String,
  columns: Seq[DataColumn],
  isView: Boolean,
) {
  def scalaName = NameFormat.sanitizeScalaName(NameFormat.toPascalCase(name))
}

case class DataEnumValue(
  name: String
) {
  def scalaName = NameFormat.sanitizeScalaName(NameFormat.toPascalCase(name))
}

case class DataEnum(
  name: String,
  values: Seq[DataEnumValue],
) {
  def scalaName = NameFormat.sanitizeScalaName(NameFormat.toPascalCase(name))
}

case class DataSchema(
  name: String,
  tables: Seq[DataTable],
  enums: Seq[DataEnum],
) {
  def scalaName = NameFormat.sanitizeScalaName(NameFormat.toCamelCase(name))
}
